name: Lint

on:
  push:
  pull_request:

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Setup V
        uses: vlang/setup-v@v1.3

      - uses: actions/checkout@v3

      - name: Check Formatting
        run: v fmt -verify .
